# SITE CONFIGURATION
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://awesome-blossom.github.io" # the base hostname & protocol for your site

# THEME-SPECIFIC CONFIGURATION
theme_settings:
  # Meta
  title: Abey Varghese
  avatar: avatar.png
  gravatar: # Email MD5 hash
  description: "A website with blog posts and pages" # used by search engines

  # Header and footer text
  header_text: >
     <h1>Aspring Web & IoT Developer</h1>
  header_text_feature_image:
  footer_text: >
   Powered by <a href="http://jekyllrb.com">Jekyll</a> with <a href="https://rohanchandra.github.io/project/type/">Type Theme</a>

  # Icons
  rss: false
  email_address: "acvarg@gmail.com"
  behance:
  bitbucket:
  facebook: "https://www.facebook.com/abey.varghese.75"
  flickr:
  github: "https://github.com/Awesome-Blossom/"
  google_plus: "https://plus.google.com/u/0/+AbeyVarghese_AB"
  instagram: "joeykirk"
  linkedin:  "https://www.linkedin.com/in/abey-varghese-775b6950/"
  pinterest:
  reddit:
  soundcloud:
  stack_exchange: "https://stackexchange.com/users/6603843/user5101226"
  steam:
  tumblr:
  twitter: "joeykirk"
  wordpress:
  youtube:

  # Scripts
  google_analytics: "UA-110117065-1"
  disqus_shortname:
  katex: true # Enable if using math markup

  # Localization strings
  str_follow_on: "Follow on"
  str_rss_follow: "Follow RSS feed"
  str_email: "Email"
  str_next: "Next"
  str_prev: "Prev"
  str_continue_reading: "Continue reading"

  # Colours, typography and padding
  # Open the "_sass > base" folder, and open "_variables.scss"
  google_fonts: "Source+Sans+Pro:400,700,700italic,400italic"

# PAGINATION
paginate: 5
paginate_path: "blog/page:num"

# COLLECTIONS
collections:
  portfolio:
    output: true

# BUILD SETTINGS
markdown: kramdown
sass:
  sass_dir: _sass
  style: :compressed

gems: [jekyll-paginate]